[languages.fa]
weight = 2
title = "AutoBSC-Fa"
languageName = "Persian"
languageCode = "fa"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"
